export default {
  LOGIN: 'Login',
  REGISTER: 'Register',
  AUTHENTICATION: 'Authentication',
  USER_PROFILE_DATA: 'FillUserProfile',
  MAIN: 'Main',
  MAIN_LIST: 'MainList',
  PICS_LIST: 'PicsList',
  SETTINGS: 'Settings',
  SETTINGS_STACK: 'SettingsStack',
  CAMERA: 'Camera',
  CAMERA_STACK: 'CameraStack',
  LIKES_MENTIONS: 'LikesMentions',
  COMMENTS: 'Comments',
  SEARCH_USER_STACK: 'SearchUserStack',
  SEARCH_USER: 'SearchUser',
  USER_FEED: 'UserFeed',
  USER_FEED_STACK: 'UserFeedStack',
}
